Tech/2 15/test page
ExadelSandbox/project pull request #23
Opened 2021-07-14 08:55 UTC by boburwebdev

Added test page

2021-07-14 09:03 UTC, YanaBr commented
Please, change base branch to 'dev' by clicking on Edit button

2021-07-14 11:32 UTC, KotdenGit commented
mat-align-tabs= This thing is not used here. Don't need it?

2021-07-14 11:33 UTC, KotdenGit approved these changes

2021-07-14 11:53 UTC, YanaBr requested changes
Please, rename component, add module for it and perform cleanup

2021-07-14 18:27 UTC, KuznetsovR commented
Why so many rows were added to the package-lock?

2021-07-14 19:55 UTC, ozhurova commented
Why the name is task  [2-5]? It's name the Footer task

2021-07-15 14:07 UTC, YanaBr commented on exalearn-ui/src/app/app.module.ts
> +import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
Do we need it inside appModule? Maybe move it under your testPageModule?

2021-07-15 14:07 UTC, YanaBr commented on exalearn-ui/src/app/components/timer/timer.component.scss
> +		font-size: 20px;
Really bad practice to use tags as a selector. Please, add specific class to this div tag and use it here

2021-07-15 14:07 UTC, YanaBr commented on exalearn-ui/src/app/components/timer/timer.component.scss
> +		font-size: 20px;
Check if we have font constant suitable to this situation (and then you can import just base.scss file instead colors and fonts

2021-07-15 14:07 UTC, YanaBr commented on exalearn-ui/src/app/components/timer/timer.component.ts
> +const TEST_DURATION = 3600;
We need to make component flexible and give the ability to set the time duration through a custom attribute
(Just put at least TODO: ... to make it later)

2021-07-15 14:07 UTC, YanaBr commented on exalearn-ui/src/app/components/timer/timer.component.ts
> +		const displayTimeLeft = () => {
Please, move displayTimeLeft to the separate function

2021-07-15 14:07 UTC, YanaBr commented on exalearn-ui/src/app/pages/main-page/main-page.component.scss
> +		color: $white;
Same as above, set up specific class to such `<a>` tag (for instance 'routing-link', but it's up to you)

2021-07-15 14:57 UTC, boburwebdev commented on exalearn-ui/src/app/app.module.ts
> +import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
I'll move it

2021-07-15 14:58 UTC, boburwebdev commented on exalearn-ui/src/app/components/timer/timer.component.scss
> +		font-size: 20px;
Got it

2021-07-15 14:58 UTC, boburwebdev commented on exalearn-ui/src/app/components/timer/timer.component.scss
> +		font-size: 20px;
Got it

2021-07-15 17:56 UTC, YanaBr approved these changes

2021-07-15 18:28 UTC, merged