[2-37] UI: Rebase header and footer
ExadelSandbox/project pull request #41
Opened 2021-07-17 15:52 UTC by HrebenYury

2021-07-17 16:05 UTC, ozhurova approved these changes

2021-07-18 12:33 UTC, KuznetsovR approved these changes

2021-07-19 09:13 UTC, YanaBr requested changes
Please, investigate can we use 2 router-outlets. One is inside main-page to navigate between our core pages/components and drop header and footer inside the main-page and second to navigate between login and main page

2021-07-19 09:24 UTC, KotdenGit approved these changes

2021-07-19 12:01 UTC, closed without merging