[2-17]/component/audition-module
ExadelSandbox/project pull request #45
Opened 2021-07-19 11:10 UTC by GeranSkot

Added : 1. Audition component. 2. Audition module. 3. Audio-cloud.service (mock) 4. Audition service. Refactored code. Sorry for merging from that branch, approve plz :D

2021-07-19 11:41 UTC, KotdenGit commented
All changes should be poured into the branch -dev.

2021-07-19 21:14 UTC, GeranSkot commented
Sorry for this mess, I'll explain myself today

2021-07-20 06:53 UTC, vstrabko reviewed
Everything looks nice, but a couple of comments need to be addressed.
Did you check how audio module looks in mobile view?

2021-07-20 06:53 UTC, vstrabko commented on exalearn-ui/src/app/services/audition.service.ts
> +}
It seems that pausing audio wastes your attempt. Is it expected?
Can we at least warn user about it before the audio starts?

Maybe we should warn the user that the audio will start and disable pause button?

2021-07-20 06:53 UTC, vstrabko commented on exalearn-ui/src/app/services/utils.service.ts
> +}
Good job!

2021-07-20 07:11 UTC, vstrabko approved these changes

2021-07-20 08:07 UTC, YanaBr commented on exalearn-ui/src/app/components/audition/audition.component.html
> +					>
Please, move this lonely bracket

2021-07-20 09:11 UTC, YanaBr requested changes
Please use whole grammar component inside your autdition

2021-07-20 09:11 UTC, YanaBr commented on exalearn-ui/src/app/components/audition/audition.component.html
> +			<h1 class="attempts" *ngIf="NumberOfAttempts != 3">{{3 - NumberOfAttempts}} attempts left</h1>
Maybe we can make it more flexible and configurable?

2021-07-20 09:11 UTC, YanaBr commented on exalearn-ui/src/app/components/audition/audition.component.html
> +				(click)="currentIndex < questions.length - 1 ? currentIndex = currentIndex + 1: currentIndex"
Please move it to separate file

2021-07-20 13:06 UTC, HrebenYury approved these changes

2021-07-20 13:57 UTC, KotdenGit approved these changes

2021-07-20 19:11 UTC, YanaBr approved these changes

2021-07-20 19:18 UTC, merged