Ahayel/28 user service tests
ExadelSandbox/project pull request #86
Opened 2021-07-28 20:40 UTC by artemgael96

2021-07-29 08:36 UTC, RomanMRC commented on exalearn-api/ExaLearn.Tests/Services/UserServiceTests.cs
> +            var service = new UserService(_mockUserRepository.Object, _mockHistoryRepository.Object, _mapper);
add field IUserService _userService = new UserService(_mockUserRepository.Object, _mockHistoryRepository.Object, _mapper);

2021-07-29 08:39 UTC, RomanMRC commented on exalearn-api/ExaLearn.Tests/Services/UserServiceTests.cs
> +            var service = new UserService(_mockUserRepository.Object, _mockHistoryRepository.Object, _mapper);
take away to field

2021-07-29 10:59 UTC, ExadelSandbox reviewed
need work

2021-07-29 11:00 UTC, ExadelSandbox requested changes, later dismissed

2021-07-29 11:00 UTC, ExadelSandbox commented on exalearn-api/ExaLearn.Tests/Fixtures/UserServiceFixture.cs
> +﻿using ExaLearn.Dal.Entities;
delete the file

2021-07-29 11:00 UTC, ExadelSandbox commented on exalearn-api/ExaLearn.Tests/Services/UserServiceTests.cs
> +            _mockHistoryRepository.Setup(x => x.GetUserHistoryByIdAsync(It.IsAny<int>())).Returns(UserServiceFixture.GetListHistoryAsync());
remade

2021-07-30 11:44 UTC, RomanMRC commented on exalearn-api/ExaLearn.Tests/Services/UserServiceTests.cs
> +            //_mockUserRepository.Setup(x => x.GetByIdAsync(It.IsAny<int>()))
remove comments

2021-07-30 11:44 UTC, RomanMRC commented on exalearn-api/ExaLearn.Tests/Services/UserServiceTests.cs
> +            IUserService _userService = new UserService(_mockUserRepository.Object, _mockHistoryRepository.Object, _mockMapper.Object);
comman field

2021-07-30 11:44 UTC, RomanMRC commented on exalearn-api/ExaLearn.Tests/Services/UserServiceTests.cs
> +            var history = UserServiceFixture.GetIdAsync();
spaces between AAA

2021-07-31 08:03 UTC, RomanMRC commented on exalearn-api/ExaLearn.Tests/Services/UserServiceTests.cs
> +                    return await new Task<User>(() => new User() { Email = "adminexa@mailnesia.com" });
Is it necessary?

2021-07-31 08:03 UTC, RomanMRC commented on exalearn-api/ExaLearn.Tests/Services/UserServiceTests.cs
> +                    return await new Task<User>(() => new User() { Email = "adminexa@mailnesia.com" });
Where start

2021-07-31 08:06 UTC, RomanMRC commented on exalearn-api/ExaLearn.Tests/Services/UserServiceTests.cs
> +        public async Task GetHrUserHistoryByIdAsync_HrHistoryModelIsValid()
Check naming method name_scenario_expected result

2021-07-31 08:14 UTC, artemgael96 commented on exalearn-api/ExaLearn.Tests/Services/UserServiceTests.cs
> +        public async Task GetHrUserHistoryByIdAsync_HrHistoryModelIsValid()
fixed

2021-07-31 08:14 UTC, artemgael96 commented on exalearn-api/ExaLearn.Tests/Services/UserServiceTests.cs
> +                    return await new Task<User>(() => new User() { Email = "adminexa@mailnesia.com" });
fixed

2021-07-31 09:00 UTC, RomanMRC approved these changes

2021-07-31 09:00 UTC, RomanMRC commented on exalearn-api/ExaLearn.Bl/Mapping/UserProfile.cs
> +                .ForMember(x => x.FullName, map => map.MapFrom(source => source.User.FirstName + " " + source.User.LastName))
string interpolation

2021-07-31 09:53 UTC, artemgael96 commented on exalearn-api/ExaLearn.Bl/Mapping/UserProfile.cs
> +                .ForMember(x => x.FullName, map => map.MapFrom(source => source.User.FirstName + " " + source.User.LastName))
fixed

2021-07-31 09:57 UTC, ElenaBurak approved these changes

2021-07-31 10:01 UTC, merged